### ISSUE TITLE
Kanban board for Recipes App group project

### ISSUE THREAD

**Issue by Danie12345** [Danie12345/recipe-app#18]
Recipe App [kanban board](https://github.com/users/Danie12345/projects/3/views/1)

Team members (2):
  - @devMahmoud - Member A
  - @Danie12345 - Member B

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @Danie12345 and @devMahmoud 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
